adding GEONOR and KSS to collection keywords
metno/mmd pull request #253
Opened 2024-06-06 14:45 UTC by ferrighi

Support for filtering of data going towards genorge and additional tags for KSS. This Closes #251

2024-06-07 07:54 UTC, mortenwh requested changes
A few suggestions that might improve it a bit :)

2024-06-07 07:54 UTC, mortenwh commented on doc/ch04-md-contrvocabs.adoc
> +|KSS |Datasets from the Norsk klimaservicesenter (Norwegian Centre for Climate Services).
I wouldn't mix languages - what about the following?
```suggestion
|KSS |Datasets from the Norwegian Centre for Climate Services (no: Norsk klimaservicesenter).
```

2024-06-07 07:54 UTC, mortenwh commented on doc/ch04-md-contrvocabs.adoc
> +
perhaps provide the link to Geonorge?

2024-06-07 07:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.ttl
> +  skos:member <https://vocab.met.no/mmd/Collection_Keywords/CC>, <https://vocab.met.no/mmd/Collection_Keywords/NMAP>, <https://vocab.met.no/mmd/Collection_Keywords/ADC>, <https://vocab.met.no/mmd/Col
Seems you forgot KSS?

2024-06-07 07:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.ttl
> +  skos:member <https://vocab.met.no/mmd/Collection_Keywords/CC>, <https://vocab.met.no/mmd/Collection_Keywords/NMAP>, <https://vocab.met.no/mmd/Collection_Keywords/ADC>, <https://vocab.met.no/mmd/Col
no, I see it now.. To help readability, then - I suggest a line shift between each entry

2024-06-07 07:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.ttl
> +  skos:definition "Datasets from the Norsk klimaservicesenter (Norwegian Centre for Climate Services)."@en .
Same as above:
```suggestion
  skos:definition "Datasets from the Norwegian Centre for Climate Services."@en .
  skos:definition "Datasett fra Norsk klimaservicesenter."@no .
```

2024-06-07 07:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.ttl
> +  skos:definition "Datasets relevant for Geonorge."@en .
```suggestion
  skos:definition "Datasets that shall be findable at Geonorge (https://geonorge.no)."@en .
```

2024-06-07 07:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.xml
> +        <skos:definition xml:lang="en">Datasets from the Norsk klimaservicesenter (Norwegian Centre for Climate Services).</skos:definition>
same language confusion here

2024-06-07 07:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.xml
> +        <skos:definition xml:lang="en">Datasets relevant for Geonorge</skos:definition>
```suggestion
        <skos:definition xml:lang="en">Datasets that shall be findable at Geonorge (https://geonorge.no)</skos:definition>
```

2024-06-10 07:19 UTC, ferrighi commented
Thanks, I'll fix and merge.

2024-06-10 07:32 UTC, merged