add organisations to vocab and add xslt to Norsk Profil ISO
metno/mmd pull request #254
Opened 2024-06-11 11:19 UTC by ferrighi

Closes #252 

- Added Organisation mapping to vocab (to be used to provide Norwegian names to genorge)
- Added dedicated mmd-to-Noiso to generalise mmd-to-genorge

2024-06-14 08:38 UTC, ferrighi commented
I've found an issue on the xslt, for a special case. I'll fix this first.

2024-06-19 12:33 UTC, ferrighi commented
The issues of duplicate personnel should be fixed now.

2024-06-20 12:54 UTC, mortenwh requested changes
LGTM - except two language corrections

2024-06-20 12:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.ttl
> +  skos:definition "A controlled vocabulary for the organisations names in English and Norwegian"@en ;
```suggestion
  skos:definition "A controlled vocabulary for the organisation names in English and Norwegian"@en ;
```

2024-06-20 12:54 UTC, mortenwh commented on thesauri/mmd-vocabulary.xml
> +    <skos:definition xml:lang="en">A controlled vocabulary for the organisations names in English and Norwegian</skos:definition>
```suggestion
    <skos:definition xml:lang="en">A controlled vocabulary for organisation names in English and Norwegian</skos:definition>
```

2024-06-20 13:37 UTC, ferrighi commented
Thanks! I've made the changes.

2024-06-20 13:37 UTC, merged